# Build stage
FROM golang:alpine AS builder
WORKDIR /app
RUN apk add --no-cache git nodejs npm
COPY . .
RUN cd frontend && npm ci && npm run build
RUN go mod tidy
RUN CGO_ENABLED=0 go build -tags server -ldflags="-s -w" -o rewyt .

# Runtime stage
FROM ghcr.io/xymaxim/ypb:latest

LABEL org.opencontainers.image.title="Rewyt"
LABEL org.opencontainers.image.description="A desktop app for rewatching YouTube live streams."
LABEL org.opencontainers.image.source="https://github.com/xymaxim/rewyt"
LABEL org.opencontainers.image.licenses="AGPL-3.0-or-later"

COPY --from=builder /app/rewyt /usr/local/bin/rewyt

COPY --chmod=755 containers/entrypoint.sh /entrypoint.sh

WORKDIR /

ENV HOME=/root

EXPOSE 3000
ENV WAILS_SERVER_HOST=0.0.0.0

ENTRYPOINT ["/entrypoint.sh"]
