// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DependencyStatus {
    /**
     * Creates a new DependencyStatus instance.
     * @param {Partial<DependencyStatus>} [$$source = {}] - The source object to create the DependencyStatus.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependencyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DependencyStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DependencyStatus(/** @type {Partial<DependencyStatus>} */($$parsedSource));
    }
}
