// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CancelStreamStart cancels the current stream startup
 * @returns {$CancellablePromise<void>}
 */
export function CancelStreamStart() {
    return $Call.ByID(98382036);
}

/**
 * Shutdown is called when the service shuts down
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(944399628);
}

/**
 * StartStream starts a new stream
 * @param {string} videoID
 * @returns {$CancellablePromise<void>}
 */
export function StartStream(videoID) {
    return $Call.ByID(1343823498, videoID);
}
