// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStreamStart():Promise<void>;

export function StartStream(arg1:string):Promise<void>;
