name: Build and Push to ghcr.io

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: |
            latest
            ${{ github.ref_name }}
          containerfiles: |
            ./containers/Containerfile

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io

  publish-compose:
    needs: publish-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install oras
        uses: oras-project/setup-oras@v1

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Fetch ypb's .env
        run: |
          mkdir ypb-compose
          oras pull ghcr.io/xymaxim/ypb-compose:latest -o ypb-compose
          cp ypb-compose/.env .env

      - name: Push compose.yaml as OCI artifact
        run: |
          cd containers
          oras push \
            --artifact-type application/vnd.docker.compose.project \
            --annotation org.opencontainers.image.title="Rewyt Compose" \
            --annotation org.opencontainers.image.description="Compose file to run Rewyt with PO token provider" \
            --annotation org.opencontainers.image.source=https://github.com/${{ github.repository }} \
            --annotation org.opencontainers.image.version=${{ github.ref_name }} \
            ghcr.io/${{ github.repository }}-compose:latest \
            compose.yaml .env
          oras push \
            --artifact-type application/vnd.docker.compose.project \
            --annotation org.opencontainers.image.title="Rewyt Compose" \
            --annotation org.opencontainers.image.description="Compose file to run Rewyt with PO token provider" \
            --annotation org.opencontainers.image.source=https://github.com/${{ github.repository }} \
            --annotation org.opencontainers.image.version=${{ github.ref_name }} \
            ghcr.io/${{ github.repository }}-compose:${{ github.ref_name }} \
            compose.yaml .env
