name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'website/**'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      # Install frontend deps
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: cd frontend && npm install

      # Build website
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: |
          cd website
          bun install --frozen-lockfile
          bunx svelte-kit sync
          bun run build

      # Build docs
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.5.2'

      - name: Add mdBook variables
        run: cargo install mdbook-variables

      - name: Add mdBook cmdrun 
        run: cargo install --git https://github.com/roberth/mdbook-cmdrun --branch mdbook-0.5

      - name: Build docs
        run: cd docs && mdbook build

      # Prepare deployment directories
      - name: Prepare pages
        run: |
          mkdir -p gh-pages
          mkdir -p gh-pages/docs
          cp -r website/build/* gh-pages/
          cp -r docs/book/* gh-pages/docs/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
